import util
MATERIAL_INVALID = 0
MATERIAL_CONCRETE = 1
MATERIAL_WOOD = 2
MATERIAL_METAL = 3
MATERIAL_GLASS = 4
MATERIAL_CARDBOARD = 5
MATERIAL_GRASS = 6
MATERIAL_GRAVEL = 7
MATERIAL_PLASTIC = 8
MATERIAL_CARPET = 9
MATERIAL_STONE = 10
MATERIAL_WATER = 11
MATERIAL_METALGRATE = 12
MATERIAL_RUBBERMATS = 13
CLIMBABLE_FLAG = 65536 | MATERIAL_CONCRETE
LADDERTOP_FLAG = 131072 | MATERIAL_CONCRETE
DEFAULT_MATERIAL = MATERIAL_CONCRETE
MATERIAL_INDEXES = [MATERIAL_CONCRETE,
 MATERIAL_WOOD,
 MATERIAL_METAL,
 MATERIAL_GLASS,
 MATERIAL_CARDBOARD,
 MATERIAL_GRASS,
 MATERIAL_GRAVEL,
 MATERIAL_PLASTIC,
 MATERIAL_CARPET,
 MATERIAL_STONE,
 MATERIAL_WATER,
 MATERIAL_METALGRATE,
 MATERIAL_RUBBERMATS]
MATERIAL_NAMES = {u'Invalid': MATERIAL_INVALID,
 u'Concrete': MATERIAL_CONCRETE,
 u'Wood': MATERIAL_WOOD,
 u'Metal': MATERIAL_METAL,
 u'Glass': MATERIAL_GLASS,
 u'Cardboard': MATERIAL_CARDBOARD,
 u'Grass': MATERIAL_GRASS,
 u'Gravel': MATERIAL_GRAVEL,
 u'Plastic': MATERIAL_PLASTIC,
 u'Carpet': MATERIAL_CARPET,
 u'Stone': MATERIAL_STONE,
 u'Water': MATERIAL_WATER,
 u'MetalGrate': MATERIAL_METALGRATE,
 u'RubberMats': MATERIAL_RUBBERMATS,
 u'Climbable': CLIMBABLE_FLAG,
 u'LadderTop': LADDERTOP_FLAG}
exports = util.AutoExports('materialTypes', globals())

