import autoexec_server_core
import log
import eveLog
startInline = ['config', 'dataconfig']
startServices = ['http',
 'cache',
 'i2',
 'languageSvc',
 'dogmaIM',
 'charMgr',
 'ship',
 'station',
 'beyonce',
 'keeper',
 'director',
 'factory',
 'standing2',
 'agentMgr',
 'LSC',
 'slash',
 'skillMgr',
 'corpStationMgr',
 'account',
 'petitioner',
 'watchdog',
 'lien',
 'effectCompiler',
 'billingMgr',
 'corpRegistry',
 'pathfinder',
 'allianceRegistry',
 'warRegistry',
 'onlineStatus',
 'market',
 'authentication',
 'emailreader',
 'dungeonExplorationMgr',
 'jumpCloneSvc',
 'jumpbeaconsvc',
 'facWarMgr',
 'damageTracker',
 'wormholeMgr',
 'infoGatheringMgr',
 'sovMgr',
 'communityClient',
 'mailMgr',
 'calendarMgr',
 'contactSvc',
 'notificationMgr',
 'voiceMgr',
 'voiceAdminMgr',
 'processHealth',
 'taleMgr',
 'taleDistributionMgr',
 'http',
 'http2',
 'devToolsProvider']
if prefs.GetValue('enableDust', 0):
    dustServices = ['catma',
     'dust',
     'dustBattle',
     'miniFramework',
     'dustInventory',
     'dustDataLog',
     'dustAccounting',
     'dustEveChat',
     'dustOrbitalStrike',
     'dustBattleSpawner']
    startServices += dustServices
autoexec_server_core.StartServer(startServices, startInline=startInline, serviceManagerClass='EveServiceManager')

