AI_SCHEMA = 'zai'
_AI_PREFIX = AI_SCHEMA + '.'
DECISION_TREE_NPC_TYPE_LINK_TABLE_FULL_NAME = _AI_PREFIX + 'decisionTreeNPCTypeLinks'
SELECT_DECISION_TREE_ROOT = 'SelectDecisionTreeRoot'
SELECT_DECISION_TREE_NODE = 'SelectDecisionNode'
DECISION_NODE_TYPES = (DECISION_NODE_NONE, DECISION_NODE_ROOT, DECISION_NODE_IF, DECISION_NODE_TASK,) = [None] + range(3)
DECISON_NODE_TYPE_NAMES = {DECISION_NODE_NONE: '<NONE>',
 DECISION_NODE_ROOT: 'root node',
 DECISION_NODE_IF: 'if node',
 DECISION_NODE_TASK: 'task node'}
PRIORITY_DEFAULT_VALUE = 0

