LOCALIZATION_SCHEMA = 'zlocalization'
MESSAGES_TABLE = 'zlocalization.messages'
MESSAGE_TEXTS_TABLE = 'zlocalization.messageTexts'
MESSAGE_GROUPS_TABLE = 'zlocalization.messageGroups'
WORD_PROPERTIES_TABLE = 'zlocalization.wordProperties'
WORD_TYPES_TABLE = 'zlocalization.wordTypes'
WORD_METADATA_TABLE = 'zlocalization.wordMetaData'
LANGUAGE_CODE_TABLE = 'zlocalization.languageCodes'
EXTERNAL_REGISTRATION_TABLE = 'zlocalization.registeredResources'
MESSAGE_MAPPING_TABLE = 'zlocalization.keyToMessageMappings'
LOC_PROJECT_TABLE = 'zlocalization.projects'
PROJECT_MESSAGE_TABLE = 'zlocalization.projectsToMessages'
PROJECT_GROUP_TABLE = 'zlocalization.projectsToGroups'
BASIC_TABLES = [MESSAGES_TABLE,
 MESSAGE_TEXTS_TABLE,
 MESSAGE_GROUPS_TABLE,
 WORD_PROPERTIES_TABLE,
 WORD_METADATA_TABLE]
LOCALE_SHORT_ENGLISH = 'en-us'
LOCALE_SHORT_RUSSIAN = 'ru'
LOCALE_SHORT_JAPANESE = 'ja'
ISO639_TO_LOCALE_SHORT = {'EN': 'en-us',
 'RU': 'ru',
 'JA': 'ja',
 'P1': 'P1'}
CODE_UNIVERSAL = 'Universal'
LOCALE_ID_ENGLISH = 1033
LOCALE_PSEUDOLOC = 'P1'
REGISTERED_TYPE_BSD = 1
REGISTERED_TYPE_DYNAMIC = 2
GENDER_MALE = 0
GENDER_FEMALE = 1
GENDER_NEUTER = 2
GENDERS_UNDEFINED = 0
GENDERS_EXACTLY_ONE_MALE = 1
GENDERS_EXACTLY_ONE_FEMALE = 2
GENDERS_AT_LEAST_ONE_MALE = 3
GENDERS_ALL_FEMALE = 4
HARDCODED_STRING_DETECTION = 0
GERMAN_SIMULATION = 1
RUSSIAN_SIMULATION = 2
JAPANESE_SIMULATION = 3
NO_REPLACEMENT = 0
DIACRITIC_REPLACEMENT = 1
CYRILLIC_REPLACEMENT = 2
DOUBLE_BYTE_REPLACEMENT = 3
DEFAULT_DECIMAL_PLACES = 6
DEFAULT_LEADING_ZEROES = 0
FOLDER_NAME_CHAR_SEPARATOR = '/'
EXPORT_XML_TEXT_ROOT = 'CCP_textData'
EXPORT_XML_META_ROOT = 'CCP_metaData'
EXPORT_XML_TRANSLATIONS = 'translations'
EXPORT_XML_METADATA = 'metadata'
EXPORT_XML_MESSAGE = 'message'
EXPORT_XML_DESCRIPTION = 'description'
EXPORT_XML_TEXT = 'text'
EXPORT_XML_MESSAGEID = 'messageID'
EXPORT_XML_DATAID = 'dataID'
EXPORT_XML_PATH = 'path'
EXPORT_XML_STATUS = 'status'
EXPORT_XML_TRANSLATE = 'Translate'
COLUMN_TEXT = 'text'
COLUMN_MESSAGEID = 'messageID'
COLUMN_LABEL = 'label'
COLUMN_FULLPATH = 'FullPath'
COLUMN_LANGUAGEID = 'languageID'
COLUMN_PROPERTY_NAME = 'propertyName'
COLUMN_TYPE_ID = 'wordTypeID'
COLUMN_PROPERTY_ID = 'wordPropertyID'
COLUMN_METADATA_VALUE = 'metaDataValue'
COLUMN_LANGUAGE_CODE_STRING = 'languageCodeString'
COLUMN_TYPE_NAME = 'typeName'
COLUMN_SCHEMA_REG_NAME = 'schemaRegName'
COLUMN_TABLE_REG_NAME = 'tableRegName'
COLUMN_COLUMN_REG_NAME = 'columnRegName'
COLUMN_TABLE_REG_ID = 'tableRegID'
COLUMN_KEY_ID = 'keyID'
BUNDLE_MESSAGE = 'Message'
BUNDLE_GROUP = 'MessageGroup'
BUNDLE_METADATA = 'WordMetaData'

