SCHEMA_NAME = 'zres'
GRAPHICS_TABLE_NAME = 'graphics'
DIRECTORIES_TABLE_NAME = 'directories'
DETAIL_MESHES_TABLE_NAME = 'detailMeshes'
GRIDS_TABLE_NAME = 'customGrids'
GRAPHICS_FULL_TABLE_NAME = SCHEMA_NAME + '.' + GRAPHICS_TABLE_NAME
DIRECTORIES_FULL_TABLE_NAME = SCHEMA_NAME + '.' + DIRECTORIES_TABLE_NAME
DETAIL_MESHES_FULL_TABLE_NAME = SCHEMA_NAME + '.' + DETAIL_MESHES_TABLE_NAME
GRIDS_FULL_TABLE_NAME = SCHEMA_NAME + '.' + GRIDS_TABLE_NAME
SELECT_DIRECTORY = 'SelectGraphicDirectory'
SELECT_GRAPHIC = 'SelectGraphic'
AUDIOMARKER_RES_PATH = 'res:/Tools/AudioMarker/AudioMarker_01.red'
WORLD_SPACE_JESSICA_PORTAL_RES_PATH = 'res:/Tools/PortalMarker/portal.red'
WORLD_SPACE_PORTAL_RES_PATH = 'res:/Tools/PortalMarker/portal_ingame.red'
WORLD_SPACE_PORTAL_LOADING_RES_PATH = 'res:/Tools/PortalMarker/portal_ingame_loading.red'

