import blue
DEFAULT_WORLD_SPACE_ID = 2353
DEFAULT_DISTRICT = 3
TEST_WORLD_SPACE_ID = 2353
TEST_KILOMETER_SPACE_ID = 2342
TEST_DISTRICT_ID = 2
INVALID_WORLDSPACE_ID = 0
BEGINNER_HAVEN_WORLDSPACE_ID = 2314
VALID_HAVEN_WORLDSPACE_IDS = [BEGINNER_HAVEN_WORLDSPACE_ID]
PAPERDOLLING_WORLDSPACE_ID = 2348
CHARACTER_CREATION_WORLDSPACE_ID = 2343
CHARACTER_SELECTION_WORLDSPACE_ID = 2345
FLOATING_POINT_EPSILON = 0.0001
PORTAL_BOUNDING_BOX = ((-1.05, -0.05, -0.5), (1.05, 3.05, 0.5))
PORTAL_VERTS = ((-1.05, -0.05, -0.5),
 (-1.05, -0.05, 0.5),
 (1.05, -0.05, 0.5),
 (1.05, -0.05, -0.5),
 (1.05, 3.05, -0.5),
 (1.05, 3.05, 0.5),
 (-1.05, 3.05, 0.5),
 (-1.05, 3.05, -0.5))
WORLD_SPACE_PROPERTY_INT = 0
WORLD_SPACE_PROPERTY_FLOAT = 1
WORLD_SPACE_PROPERTY_STRING = 2
WORLD_SPACE_PROPERTY_COLOR = 3
WORLD_SPACE_PROPERTY_BOOL = 4
WOD_BUILDING = 'trinity.WodBuilding'
WOD_PLACEABLE = 'trinity.WodPlaceable'
WOD_INTERIOR_PLACEABLE = 'trinity.Tr2InteriorPlaceable'
INTERIOR_STATIC = 'trinity.Tr2InteriorStatic'
BLUETYPE_TO_RESPATH_ATTRNAME = {WOD_BUILDING: 'buildingResPath',
 WOD_PLACEABLE: 'placeableResPath',
 WOD_INTERIOR_PLACEABLE: 'placeableResPath',
 INTERIOR_STATIC: 'interiorStatic'}
TYPE_OBJECT = 'object'
TYPE_PORTAL = 'portal'
TYPE_LIGHT = 'light'
TYPE_OCCLUDER = 'occluder'
TYPE_PHYSICAL_PORTAL = 'physicalPortal'
TYPE_PROBE_VOLUME = 'probeVolume'
TYPE_AUDIO = 'audio'
TYPE_ITEM = 'item'
TYPE_LOCATOR = 'locator'
TYPE_AREA = 'area'
TYPE_NPC = 'npc'
TYPE_GENERATOR = 'generator'
ROOM_EDIT_GRID_TYPE_FLOOR = 0
ROOM_EDIT_GRID_TYPE_WALL = 1
ROOM_EDIT_GRID_TYPE_CEILING = 2
ROOM_EDIT_GRID_TYPE_SURFACE = 3
WORLD_SPACE_EDITOR = 'World Space Editor'
WORLD_SPACE_PROPERTY_TYPE_EDITOR = 'World Space Property Types'
STATIC_OBJECT_EDITOR = 'Static Objects'
CELL_EDITOR = 'Cell Manager'
if '/wodworld' in blue.pyos.GetArg():
    WORLD_SPACE_SCHEMA = 'world'
else:
    WORLD_SPACE_SCHEMA = 'zworld'
GAME_WORLD_SPACE_SCHEMA = 'world'
_WORLD_SPACE_PREFIX = WORLD_SPACE_SCHEMA + '.'
_GAME_WORLD_SPACE_PREFIX = GAME_WORLD_SPACE_SCHEMA + '.'
WORLD_SPACE_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'worldSpaces'
WORLD_SPACE_PROPERTIES_TABLE = _GAME_WORLD_SPACE_PREFIX + 'properties'
WORLD_SPACE_PROPERTY_TYPES_TABLE = _GAME_WORLD_SPACE_PREFIX + 'propertyTypes'
WORLD_SPACE_PROPERTY_TYPE_GROUPS_TABLE = _GAME_WORLD_SPACE_PREFIX + 'propertyTypeGroups'
DISTRICT_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'staticDistricts'
WORLD_PHYSICAL_PORTAL_MAIN_TABLE_NAME = 'physicalPortals'
WORLD_PHYSICAL_PORTAL_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_PHYSICAL_PORTAL_MAIN_TABLE_NAME
WORLD_PROBE_VOLUME_MAIN_TABLE_NAME = 'probeVolumes'
WORLD_PROBE_VOLUME_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_PROBE_VOLUME_MAIN_TABLE_NAME
WORLD_ENLIGHTEN_AREAS_MAIN_TABLE_NAME = 'enlightenAreas'
WORLD_ENLIGHTEN_AREAS_TABLE = _WORLD_SPACE_PREFIX + WORLD_ENLIGHTEN_AREAS_MAIN_TABLE_NAME
WORLD_LIGHTS_MAIN_TABLE_NAME = 'lights'
WORLD_LIGHTS_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_LIGHTS_MAIN_TABLE_NAME
WORLD_OCCLUDERS_MAIN_TABLE_NAME = 'occluders'
WORLD_OCCLUDERS_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_OCCLUDERS_MAIN_TABLE_NAME
WORLD_LIGHTS_OVERRIDES_TABLE_NAME = 'objectLightOverrides'
WORLD_LIGHTS_OVERRIDES_TABLE = _GAME_WORLD_SPACE_PREFIX + WORLD_LIGHTS_OVERRIDES_TABLE_NAME
WORLD_LOCATORS_MAIN_TABLE_NAME = 'locators'
WORLD_LOCATORS_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_LOCATORS_MAIN_TABLE_NAME
WORLD_SPACE_AUDIO_MAIN_TABLE_NAME = 'audioLocations'
WORLD_SPACE_AUDIO_TABLE = _WORLD_SPACE_PREFIX + WORLD_SPACE_AUDIO_MAIN_TABLE_NAME
WORLD_SPACE_OBJECT_MAIN_TABLE_NAME = 'objects'
WORLD_SPACE_OBJECT_MAIN_TABLE = _WORLD_SPACE_PREFIX + WORLD_SPACE_OBJECT_MAIN_TABLE_NAME
WORLD_SPACE_GROUPS_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'groups'
WORLD_SPACE_PREFAB_OBJECTS_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'staticWorldSpacePrefabObjects'
WORLD_SPACE_PREFAB_LIGHTS_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'staticPrefabLights'
WORLD_SPACE_PREFABS_MAIN_TABLE = _WORLD_SPACE_PREFIX + 'staticWorldSpacePrefabs'
WORLD_SPACE_PORTAL_MAIN_TABLE_NAME = 'portals'
WORLD_SPACE_PORTAL_MAIN_TABLE = _GAME_WORLD_SPACE_PREFIX + WORLD_SPACE_PORTAL_MAIN_TABLE_NAME
WORLD_SPACE_PORTAL_CONNECTIONS_TABLE = _GAME_WORLD_SPACE_PREFIX + 'portalConnections'
WORLD_SPACE_PORTAL_CLUSTER_MAIN_TABLE_NAME = 'portalGroups'
WORLD_SPACE_PORTAL_CLUSTER_MAIN_TABLE = _GAME_WORLD_SPACE_PREFIX + WORLD_SPACE_PORTAL_CLUSTER_MAIN_TABLE_NAME
SELECT_WORLD_SPACE = 'SelectWorldSpace'
SELECT_WORLD_SPACE_PROPERTY_TYPE = 'SelectWorldPropertyType'
SELECT_DISTRICT = 'SelectDistrict'
SELECT_PORTAL_CLUSTER = 'SelectPortalCluster'
SELECT_PREFAB = 'SelectPrefab'
WORLD_SPACE_SELECTION_EVENTS = [SELECT_WORLD_SPACE, SELECT_WORLD_SPACE_PROPERTY_TYPE]
GAMEWORLD_S_PER_TICK = 0.033
TRINITY_DRAG_WORLD_SPACE_OBJECT = 'WorldSpaceObject'
TRINITY_DRAG_WORLD_SPACE_PORTAL = 'WorldSpacePortal'
TRINITY_DRAG_WORLD_POINT_LIGHT = 'WorldPointLight'
TRINITY_DRAG_WORLD_SPOT_LIGHT = 'WorldSpotLight'
TRINITY_DRAG_WORLD_BOX_LIGHT = 'WorldBoxLight'
TRINITY_DRAG_WORLD_PHYSICAL_PORTAL = 'WorldPhysicalPortal'
TRINITY_DRAG_WORLD_PROBE_VOLUME = 'WorldProbeVolume'
TRINITY_DRAG_WORLD_SPACE_NEW_PORTAL = 'WorldSpaceNewPortal'
TRINITY_DRAG_WORLD_SPACE_NEW_OBJECT = 'WorldSpaceNewObject'
TRINITY_DRAG_WORLD_OCCLUDER = 'WorldOccluder'
TRINITY_DRAG_WORLD_PREFAB = 'WorldSpacePrefab'
TRINITY_DRAG_WORLD_GENERATOR = 'Generator'
TRINITY_DRAG_WORLD_CEF_ENTITY = 'WorldCEFEntity'
LIGHT_OVERRIDE_ATTRS = {'color': 'Color',
 'direction': 'Direction',
 'radius': 'Radius',
 'specularRadiusMultiplier': 'SpecularRadiusMultiplier',
 'pointLight': 'PointLight',
 'spotlightConeAngle': 'SpotlightConeAngle',
 'distanceFalloffKneeValue': 'DistanceFalloffKneeValue',
 'distanceFalloffKneeRadius': 'DistanceFalloffKneeRadius'}
PATHING_FOLDER = 'res:/pathing/'
PATHING_DB = 'DefaultPathing'
PATHING_DATA_FILE = 'pathingData.msl'
POSE_ERROR_ITEM_IN_USE = 'Item is already in use.'
POSE_ERROR_ITEM_IS_TO_FAR = 'You are too far away.'
HIGHLIGHT_NOT_OPEN = (0.0, 0.0, 0.0, 0.0)
HIGHLIGHT_OPEN_BY_ME = (0.2, 1.0, 0.2, 0.3)
HIGHLIGHT_OPEN_BY_OTHER = (1.0, 0.2, 0.2, 0.3)
BASIC_LIGHT = 0
BOX_LIGHT = 1
INTERIOR_SCENE = 0
EXTERIOR_FM_SCENE = 1

