ACTION_SCHEMA = 'zaction'
_ACTION_PREFIX = ACTION_SCHEMA + '.'
_ACTION_TREE_TABLE_NAME = 'trees'
_ACTION_TREE_TABLE_FULL_PATH = _ACTION_PREFIX + _ACTION_TREE_TABLE_NAME
_ACTION_TREE_LINK_TABLE_NAME = 'treeLinks'
_ACTION_TREE_LINK_TABLE_FULL_PATH = _ACTION_PREFIX + _ACTION_TREE_LINK_TABLE_NAME
ACTION_STEP_TABLE_NAME = 'steps'
ACTION_STEP_TABLE_FULL_PATH = _ACTION_PREFIX + ACTION_STEP_TABLE_NAME
ACTION_PROC_TABLE_NAME = 'procs'
ACTION_PROC_TABLE_FULL_PATH = _ACTION_PREFIX + ACTION_PROC_TABLE_NAME
_ACTION_PROPERTY_TABLE_NAME = 'properties'
_ACTION_PROPERTY_TABLE_FULL_PATH = _ACTION_PREFIX + _ACTION_PROPERTY_TABLE_NAME
ACTION_PROC_TYPE_TABLE_NAME = 'procTypes'
ACTION_PROC_TYPE_TABLE_FULL_PATH = _ACTION_PREFIX + ACTION_PROC_TYPE_TABLE_NAME
ACTION_PROC_TYPE_PROPERTY_TABLE_NAME = 'procTypeProperties'
ACTION_PROC_TYPE_PROPERTY_TABLE_FULL_PATH = _ACTION_PREFIX + ACTION_PROC_TYPE_PROPERTY_TABLE_NAME
MAX_PROP_NAME_LEN = 64
SELECT_ACTION_TREE = 'SelectActionTree'
SELECT_ACTION_STEP = 'SelectActionStep'
SELECT_ACTION_PROC = 'SelectActionProc'
ACTIONSTEP_TYPE_NORMAL = 'Normal'
ACTIONSTEP_TYPE_CONDITIONAL = 'Conditional'
ACTIONSTEP_TYPE_TRY = 'Try Until'
ACTIONSTEP_TYPE_CATCH = 'Catch'
ACTIONSTEP_TYPE_TRYSYNC = 'Try Sync'
ACTIONSTEP_TYPE_WHILE = 'While'
ACTIONSTEP_TYPEID_NORMAL = 0
ACTIONSTEP_TYPEID_CONDITIONAL = 1
ACTIONSTEP_TYPEID_TRY = 2
ACTIONSTEP_TYPEID_CATCH = 3
ACTIONSTEP_TYPEID_TRYSYNC = 4
ACTIONSTEP_TYPEID_WHILE = 5
ACTION_STEP_TYPEID_TO_STRING = (ACTIONSTEP_TYPE_NORMAL,
 ACTIONSTEP_TYPE_CONDITIONAL,
 ACTIONSTEP_TYPE_TRY,
 ACTIONSTEP_TYPE_CATCH,
 ACTIONSTEP_TYPE_TRYSYNC,
 ACTIONSTEP_TYPE_WHILE)
ACTIONSTEP_LOC_CLIENTSERVER = 'Client and Server'
ACTIONSTEP_LOC_CLIENTONLY = 'Client Only'
ACTIONSTEP_LOC_SERVERONLY = 'Server Only'
ACTIONSTEP_LOCID_CLIENTSERVER = 0
ACTIONSTEP_LOCID_CLIENTONLY = 1
ACTIONSTEP_LOCID_SERVERONLY = 2
ACTION_STEP_LOCID_TO_STRING = (ACTIONSTEP_LOC_CLIENTSERVER, ACTIONSTEP_LOC_CLIENTONLY, ACTIONSTEP_LOC_SERVERONLY)
_ACTION_INTERNAL = 0
_ACTION_EXPOSED = 1
ACTION_TREE_LINK_REFERENCE = 1
ACTION_TREE_LINK_BRANCH = 2
ACTION_TREE_LINK_TYPES = [ACTION_TREE_LINK_REFERENCE, ACTION_TREE_LINK_BRANCH]
ACTION_TREE_LINK_NAMES = {'In-Place': ACTION_TREE_LINK_REFERENCE,
 'Branch-To': ACTION_TREE_LINK_BRANCH}
_ACTION_LINK_BIT_ORDER_SPLIT = 16
_ACTION_LINK_TYPE_BIT_FILTER = 65535
_ACTION_LINK_TYPE_MAX_VALUE = 65535
_ACTION_LINK_EXPOSURE_BIT_FILTER = 4294901760L
_ACTION_LINK_EXPOSURE_MAX_VALUE = 65535
ACTION_EXPOSURE_EXTERNAL = 0
ACTION_EXPOSURE_INTERNAL = 1
ACTION_EXPOSURE_NEVER = 2
ACTION_EXPOSURE_TYPES = [ACTION_EXPOSURE_EXTERNAL, ACTION_EXPOSURE_INTERNAL, ACTION_EXPOSURE_NEVER]
ACTION_EXPOSURE_TYPE_NAMES = {'External': ACTION_EXPOSURE_EXTERNAL,
 'Internal': ACTION_EXPOSURE_INTERNAL,
 'Never': ACTION_EXPOSURE_NEVER}
ACTIONTREE_RECIPE_DEFAULT_ACTION_NAME = 'defaultAction'

