ACTIONOBJECT_SCHEMA = 'zactionobject'
_ACTIONOBJECT_PREFIX = ACTIONOBJECT_SCHEMA + '.'
ACTIONOBJECT_TABLE_NAME = 'actionObjects'
ACTIONOBJECT_TABLE_FULL_PATH = _ACTIONOBJECT_PREFIX + ACTIONOBJECT_TABLE_NAME
ACTIONSTATION_TABLE_NAME = 'actionStations'
ACTIONSTATION_TABLE_FULL_PATH = _ACTIONOBJECT_PREFIX + ACTIONSTATION_TABLE_NAME
ACTIONSTATION_ACTIONS_TABLE_NAME = 'actionStationActions'
ACTIONSTATION_ACTIONS_TABLE_FULL_PATH = _ACTIONOBJECT_PREFIX + ACTIONSTATION_ACTIONS_TABLE_NAME
ACTIONOBJECT_STATION_TABLE_NAME = 'actionObjectStations'
ACTIONOBJECT_STATION_TABLE_FULL_PATH = _ACTIONOBJECT_PREFIX + ACTIONOBJECT_STATION_TABLE_NAME
ACTIONOBJECT_EXITS_TABLE_NAME = 'actionObjectExits'
ACTIONOBJECT_EXITS_TABLE_FULL_PATH = _ACTIONOBJECT_PREFIX + ACTIONOBJECT_EXITS_TABLE_NAME

