BENCHMARK_SCHEMA = 'zbenchmark'
BENCHMARK_PREFIX = BENCHMARK_SCHEMA + '.'
WORLD_CAMERAS_TABLE_NAME = 'worldCameras'
WORLD_CAMERAS_MAIN_TABLE = BENCHMARK_PREFIX + WORLD_CAMERAS_TABLE_NAME
WORLD_AVATARS_TABLE_NAME = 'worldAvatars'
WORLD_AVATARS_MAIN_TABLE = BENCHMARK_PREFIX + WORLD_AVATARS_TABLE_NAME
SELECT_CAMERA = 'SelectCamera'
SELECT_AVATAR = 'SelectAvatar'
TRINITY_DRAG_BENCHMARK_AVATAR = 'BenchmarkAvatar'

